### ISSUE TITLE
Text entry: student feedback

### ISSUE THREAD

**Issue by andyjko** [andyjko/user-interface-software-and-technology#29]
> First, I think that a variety of predictive text entry techniques will help people type as fast as they think. Second, a variety of virtual keyboards in the future would enable users to type as fast as typing in the physical environments, and future systems might be able to track users’ hands from the keyboard. Finally, I image affective computing may be incorporated into the design of text entry techniques, predicting and indicating users’ moods and behaviors. Based on users’ hand movement and typing speed, these affective text entry devices will efficiently communicate affective states and emotions.

**Comment by andyjko** [comment]
> I love how you start with the history of the text input method. Besides, I am also very interested in knowing why some input method faded out of our life, yet some still are ongoing. For example, why the original QWERTY layout was designed to minimize mechanical failure, not speed or accuracy; The Dvorak layout was designed for speed. However, we, nowadays, are still using QWERTY?
> I am also interested in knowing the limitation of each input methods.

**Comment by andyjko** [comment]
> Here I have one idea and one suggestion for the required reading - Text entry:
For the predictive input you mentioned in the article, imagine in the future, a physical keyboard that can detect your mind, and predict the words at the same time when you thinking. I think this idea is not in the blue sky when we combine machine learning with sensors integrated into the keyboard.
> I suggest you could mention the relationship between text and input in the virtual space, such as AR, VR, MR environment. I am personally very curious about how people input text during those virtual space, and what kind of challenges they have met and how designers and engineers toggle the problems, as well as the prediction of their future development.

**Comment by andyjko** [comment]
> I LOOVVEEE the picture of the kitty on the laptop, it got me all excited to read! Please keep this forever. 
> You mentioned that"…people also need to be comfortable while they're entering text: it shouldn't hurt, it shouldn't cause fatigue, and most importantly it should be possible." Maybe this might be a point to mention that because typing has become such an important part of everyday life, there have actually been guides developed on the healthiest ways to type. Moreover, typing the wrong over time has caused people serious injuries. 
> The common theme in this chapter is that "keyboards come in numerous shapes and sizes" and you show a wide variety of them. However, one of the most common keyboards we use today - the keyboard on our smartphones - was not shown. I think this deserves a spot (i.e. an image) :)
It would be nice to see a comparison (perhaps through a video) of someone with large fingers using a keyboard on a smartphone versus someone with small or medium sized fingers. This will help in demonstrating how much physical form impacts text entry and accuracy.

**Comment by ewhitmire** [comment]
> Under each category for "discrete, continuous, and predictive," I would suggest having a clear definition for each type of input. There are plenty of examples listed under each, but it isn't entirely clear what each particular input entails. I can insinuate, for example, the qualities that make up a discrete input based on the heavy emphasis on keyboards and the QWERTY layout in that section. However, I think this chapter could be clearer and more informative if it had one simple sentence at the beginning of each section that defines the type of input.
> 
> I was particularly interested in learning about the stenotype (the photo really caught my eye), but there was no video to accompany it, let alone barely any explanation of it in the text. Because stenotypes are uncommon to the average person, yet require 2-4 years of training by stenographers(!), I would suggest giving more information on it or including a video of how it works. We did watch a video demonstration of it in class that was shown by Jake, but if he had not been guest teaching, I doubt I would have grasped the workings of it.
