### ISSUE TITLE
2D Visual Output: student feedback

### ISSUE THREAD

**Issue by andyjko** [andyjko/user-interface-software-and-technology#30]
> This chapter certainly covers a lot, most of which I suspect everyone has read a lot about, like typography or data visualization, so a paragraph or two is not super impactful. Maybe you could go a little deeper into each area, or speak only about graphics and typography and not take it beyond that? That said, it is interesting to get some of the tidbits about why we use the things we do. I'd be interested to learn more about 2d interaction and hierarchy paradigms and why we use those. Why do we scroll up and down? We tend to jump from page to page, but we could also be zooming into subscreens of main screens or something.

**Comment by halfcadence** [comment]
Where should I file proofreading issues? I just noticed this:
> ClearType, which they found significantly **increased** average reading time

**Comment by andyjko** [comment]
Good catch, thanks @halfcadence!

**Comment by andyjko** [comment]
Address OLED displays.

**Comment by ewhitmire** [comment]
> I see that there are captions for sketches/pictures/videos, but it would be beneficial to also include clear references to it within the text. So for the near-eye display video, the text right above the video could be revised to say "Some have experimented with even smaller displays, such as low-energy displays without batteries (Grosse-Puppendahl et al. 2016) or tiny displays intended to view near eyes (Lyons et al. 2014), as seen in Video 2 or the video below. This can be done for all the chapters in this book, so that references to images/videos mentioned in the text are clear and immediately connected to what you are reading at a given point.

> In the paragraph under the Graphics section that says "All of this graphical compositing is what allows us to create entire virtual worlds such as desktop interfaces or interactive 3D worlds," you don't clearly understand what compositing means. You only know what the benefit of compositing could be. To know what compositing actually entails, define compositing in the sentence prior so it could say "Compositing entails composing shapes together, and rendering them in a particular order, so that we can get buttons with backgrounds, scroll bars with depth and texture, windows with drop shadows."
