### ISSUE TITLE
Use UTF-8 encoding

### ISSUE THREAD

**Issue by ewhitmire** [andyjko/user-interface-software-and-technology#9]
Right now, all the documents are encoded as Windows-1252. This is a legacy format and UTF-8 is the default for HTML5.

I noticed this because my text editor tries to open the file as UTF-8 and all the special characters get corrupted on save.

**Comment by andyjko** [comment]
Weird. When I open them various text editors in OS X, they all show UTF-8 encoding. Can you repro for all documents or in other editors?

**Comment by ewhitmire** [comment]
Ah, I had an HTML validator extension doing something weird. You're right, they are UTF-8. Sorry about that.

**Comment by ewhitmire** [comment]
I figured out what's going on here. The documents are UTF-8 (or intended to be), but charset detection is failing in Chrome (and my text editor) and it's choosing windows-1252. Most of the time it doesn't matter because 1252 and UTF-8 overlap. Charset detection is a weird black magic in browsers. This can be easily fixed by specifying the charset in the html. I can fix this as I go through the rest of the pages.

Here's an example of when it fails and causes a problem: (Look at the Roussel entry)
http://faculty.washington.edu/ajko/books/uist/pointing.html
