### ISSUE TITLE
Pointing: change summary of Afergan paper

### ISSUE THREAD

**Issue by evanpeck** [andyjko/user-interface-software-and-technology#94]
https://github.com/andyjko/user-interface-software-and-technology/blob/08cdaac76aea28224ccadb5d72fb65fd6440a9eb/pointing.html#L178

I think the summary of the _Brain-Based Target Expansion_ paper is a bit different than how our system was designed. 

Relevant quote from the paper: 
> We propose dynamically manipulating the size of high priority targets as a function of the user’s current state. During periods of difficult multitasking, the target size of high priority targets expand, making them easier to click and the lower priority targets, in effect, comparatively evasive. Under less mentally strenuous circumstances, the size of high priority targets returns to default settings.

**Comment by andyjko** [comment]
Excellent, thank you for the feedback Evan! I'll try to fix this soon, or you're welcome to submit a pull request with a revision.
